# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_LN_Class', [dirname(__file__)])
        except ImportError:
            import _LN_Class
            return _LN_Class
        if fp is not None:
            try:
                _mod = imp.load_module('_LN_Class', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _LN_Class = swig_import_helper()
    del swig_import_helper
else:
    import _LN_Class
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class LN_Class(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LN_Class, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LN_Class, name)
    __swig_destroy__ = _LN_Class.delete_LN_Class
    __del__ = lambda self : None;
    def __init__(self, *args): 
        this = _LN_Class.new_LN_Class(*args)
        try: self.this.append(this)
        except: self.this = this
    def __add__(self, *args): return _LN_Class.LN_Class___add__(self, *args)
    def __sub__(self, *args): return _LN_Class.LN_Class___sub__(self, *args)
    def __mul__(self, *args): return _LN_Class.LN_Class___mul__(self, *args)
    def __div__(self, *args): return _LN_Class.LN_Class___div__(self, *args)
    def __mod__(self, *args): return _LN_Class.LN_Class___mod__(self, *args)
    def PowMod(self, *args): return _LN_Class.LN_Class_PowMod(self, *args)
    def ReadText(self, *args): return _LN_Class.LN_Class_ReadText(self, *args)
    def WriteText(self, *args): return _LN_Class.LN_Class_WriteText(self, *args)
    def ReadBin(self, *args): return _LN_Class.LN_Class_ReadBin(self, *args)
    def WriteBin(self, *args): return _LN_Class.LN_Class_WriteBin(self, *args)
    def __str__(self): return _LN_Class.LN_Class___str__(self)
    def __repr__(self): return _LN_Class.LN_Class___repr__(self)
LN_Class_swigregister = _LN_Class.LN_Class_swigregister
LN_Class_swigregister(LN_Class)

# This file is compatible with both classic and new-style classes.


